### PR TITLE
Latest DT Content

### PR DESCRIPTION
**Pull request by kylekirkby**

### CODE REVIEW

**Comment by kylekirkby** [comment]
@shovanuk

**Comment by shovanuk** [comment]
@kylekirkby Arm logo need to change. New logo can be found here
https://www.linaro.org/wp-content/uploads/2017/07/arm.jpg

Once Linaro is Jekyll friendly, all member logos need to be pulled from a central member database.

**Comment by kylekirkby** [comment]
New arm logo has been added @shovanuk

**Comment by shovanuk** [comment]
Signed-off-by Shovan

**Pull request merged**
